version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: cube_nodejs_express_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_nodejs_express_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_nodejs_express_redis
    ports:
      - "6379:6379"

volumes:
  cube_nodejs_express_mysql:
